# Generated by Django 3.2.18 on 2023-03-21 01:32

from django.db import migrations


def create_test_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    u = User.objects.create_superuser('admin', 'admin@myproject.com', 'admin')
    u.is_staff = True
    u.save()
    u = User.objects.create_user('guest', 'guest@myproject.com', 'guest')
    u.is_staff = True
    u.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_test_users),
    ]
